force-app/main/default/objects/Toys__c/Toys__c.object-meta.xml
<CustomObject>
    <description>Object to capture toys for sale</description>
    <label>Toys</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Toys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Toys__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Capture the description of the toy</description>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Toys__c/fields/Is_Available__c.field-meta.xml
<CustomField>
    <fullName>Is_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Captures whether the toy is available or not</description>
    <label>Is Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Toys__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Captures the price of the toy</description>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ClassToyDetailRESTTest.cls
/**
 * @description       : Test class for ClassToyDetailREST - test coverage = 88%
 * @author            : chhavi2684@gmail.com
 * @group             : 
 * @last modified on  : 08-12-2020
 * @last modified by  : chhavi2684@gmail.com
 * Modifications Log 
 * Ver   Date         Author                    Modification
 * 1.0   08-12-2020   chhavi2684@gmail.com   Initial Version
**/
@isTest
public class ClassToyDetailRESTTest {
    /* Test data setup class*/
    @TestSetup
    static void setupData() {
        Toys__c newToy = new Toys__c(Name = 'Test Toy', Description__c = 'Test Description', Is_Available__c = true, Price__c = 100);
        insert newToy;
    }
    /*Method to test positive scenario where Toys are found*/
    @isTest
	static void  getToyDetailsTest(){
        ClassToyDetailREST.RequestWrapper testToys = new ClassToyDetailREST.RequestWrapper();
        testToys.toyNames = new List<String>{'Test Toy','Not Found'};
        String testRequestString = JSON.serialize(testToys);
        RestRequest testRequest = new RestRequest(); 
        RestResponse testResponse = new RestResponse();
    	testRequest.requestURI = '/services/apexrest/ToyDetail/';  //Request URL
        testRequest.httpMethod = 'POST';//HTTP Request Type
        testRequest.requestBody = Blob.valueof(testRequestString);
        RestContext.request = testRequest;
        ClassToyDetailREST.ResponseWrapper responseObj = new ClassToyDetailREST.ResponseWrapper();
        Test.startTest();
        responseObj = ClassToyDetailREST.getToyDetails();
        Test.stopTest();
        System.assertEquals(responseObj.statusCode, 200);
   }
    /*Method to test negative scenario where Toys are not found*/
    @isTest
	static void  getToyDetailsNegativeTest(){
        ClassToyDetailREST.RequestWrapper testToys = new ClassToyDetailREST.RequestWrapper();
        testToys.toyNames = new List<String>{'Not Found'};
        String testRequestString = JSON.serialize(testToys);
        RestRequest testRequest = new RestRequest(); 
        RestResponse testResponse = new RestResponse();
    	testRequest.requestURI = '/services/apexrest/ToyDetail/';  //Request URL
        testRequest.httpMethod = 'POST';//HTTP Request Type
        testRequest.requestBody = Blob.valueof(testRequestString);
        RestContext.request = testRequest;
        ClassToyDetailREST.ResponseWrapper responseObj = new ClassToyDetailREST.ResponseWrapper();
        Test.startTest();
        responseObj = ClassToyDetailREST.getToyDetails();
        Test.stopTest();
        System.assertEquals(responseObj.statusCode, 400);
   }
}